version: '3.8'
services:
  mongodb:
    image: mongo:6.0.19
    container_name: mongodb
    restart: unless-stopped
    networks:
      - web
    ports:
      - "27017:27017"
    volumes:
      - '/opt/docker/mongodb/db:/data/db:cached' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: XXXXXXXXX
networks:
  web:
    external: true
